name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  DOCKER_REGISTRY: ghcr.io
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: 'Calculate tag names'
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.DOCKER_REGISTRY }}
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - id: repostring
      uses: ASzc/change-string-case-action@v3
      with:
        string: ${{ github.repository }}
          
    - name: Build and push Kumpel
      uses: docker/build-push-action@v3
      with:
        context: ./src/
        push: true
        tags: ${{ env.DOCKER_REGISTRY }}/${{ steps.repostring.outputs.lowercase }}/py-passwords:${{ steps.vars.outputs.sha_short }}
